# Generated by Django 4.2.11 on 2024-03-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="language",
            old_name="title",
            new_name="code",
        ),
        migrations.RemoveField(
            model_name="language",
            name="parts_of_speech",
        ),
    ]
