# Generated by Django 4.2.10 on 2024-03-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="level",
            field=models.CharField(
                choices=[("a1", "A1"), ("a2", "A2"), ("b1", "B1"), ("b2", "B2"), ("c2", "C2")],
                default="a1",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
