# Generated by Django 4.2.11 on 2024-03-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0002_rename_title_language_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="parts_of_speech",
            field=models.ManyToManyField(blank=True, to="words.partofspeech", verbose_name="Parts of Speech"),
        ),
    ]
