# Generated by Django 4.2.11 on 2024-03-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0002_language_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="language",
            old_name="name",
            new_name="title",
        ),
    ]
