# Generated by Django 4.2.11 on 2024-03-15 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0002_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="language",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="words.language"),
        ),
        migrations.AlterField(
            model_name="word",
            name="language",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="words.language"),
        ),
    ]
