# Generated by Django 4.2.11 on 2024-03-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0002_article_created_article_modified_bundle_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="article",
            new_name="title",
        ),
    ]
