# Generated by Django 4.2.10 on 2024-03-04 02:08

import apps.base.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0002_alter_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                default="defaults/word/image.jpg",
                unique=True,
                upload_to="words/",
                validators=[apps.base.utils.validators.validate_file_size],
            ),
        ),
    ]
