# Generated by Django 4.2.11 on 2024-03-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0003_alter_note_language_alter_word_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="notes",
            field=models.ManyToManyField(blank=True, to="words.note"),
        ),
    ]
