# Generated by Django 4.2.11 on 2024-03-31 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0003_rename_name_language_title"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="word",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="word",
            name="part_of_speech",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="words.partofspeech",
                verbose_name="Parts of Speech",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="parts_of_speech",
            field=models.ManyToManyField(
                blank=True, related_name="parts_of_speech", to="words.partofspeech", verbose_name="Parts of Speech"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="word",
            unique_together={("title", "language", "part_of_speech")},
        ),
    ]
