# Generated by Django 4.2.11 on 2024-03-31 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0004_alter_word_unique_together_word_part_of_speech_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="part_of_speech",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="words.partofspeech",
                verbose_name="Part of Speech",
            ),
        ),
    ]
