# Generated by Django 4.2.16 on 2024-10-26 16:10

import apps.base.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0006_remove_word_parts_of_speech"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["-created"], "verbose_name": "Image", "verbose_name_plural": "Images"},
        ),
        migrations.AlterField(
            model_name="image",
            name="description",
            field=models.TextField(blank=True, help_text="Optional description of the image.", null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                default="defaults/word/image.jpg",
                help_text="Image file associated with the vocabulary word.",
                upload_to="words/",
                validators=[apps.base.utils.validators.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(
                help_text="Alphanumeric title of the image.",
                max_length=100,
                unique=True,
                validators=[apps.base.utils.validators.validate_alphanumeric],
            ),
        ),
    ]
