export const wordsData = [
  {
    title: "Ansehen",
    sentence: "Sein Ansehen in der Schule ist sehr hoch.",
    article: "das",
    parts_of_speech: "noun",
    level: "a1",
  },
  {
    title: "Ansehen",
    sentence: "Sein Ansehen in der Schule ist sehr hoch.",
    article: "das",
    parts_of_speech: "noun",
    level: "a1",
  },
  {
    title: "Ansehen",
    sentence: "Sein Ansehen in der Schule ist sehr hoch.",
    article: "das",
    parts_of_speech: "noun",
    level: "a1",
  },
  {
    title: "Ansehen",
    sentence: "Sein Ansehen in der Schule ist sehr hoch.",
    article: "das",
    parts_of_speech: "noun",
    level: "a1",
  },
  {
    title: "Ansehen",
    sentence: "Sein Ansehen in der Schule ist sehr hoch.",
    article: "das",
    parts_of_speech: "noun",
    level: "a1",
  },
  {
    title: "Ansehen",
    sentence: "Sein Ansehen in der Schule ist sehr hoch.",
    article: "das",
    parts_of_speech: "noun",
    level: "a1",
  },
  {
    title: "Ansehen",
    sentence: "Sein Ansehen in der Schule ist sehr hoch.",
    article: "das",
    parts_of_speech: "noun",
    level: "a1",
  },
  {
    title: "Ansehen",
    sentence: "Sein Ansehen in der Schule ist sehr hoch. Sein Ansehen in der Schule ist sehr hoch.",
    article: "das",
    parts_of_speech: "noun",
    level: "a1",
  },
];
