# Generated by Django 4.2.10 on 2024-03-02 23:50

import apps.base.utils.validators
import apps.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                default="defaults/profile/picture.jpg",
                upload_to=apps.users.utils.profile_picture_directory,
                validators=[apps.base.utils.validators.validate_file_size],
            ),
        ),
    ]
