# Generated by Django 4.2.11 on 2024-03-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviewWord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("plural", models.CharField(blank=True, max_length=100, null=True)),
                ("sentence", models.TextField(blank=True, default="", null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("a1", "A1"), ("a2", "A2"), ("b1", "B1"), ("b2", "B2"), ("c1", "C1"), ("c2", "C2")],
                        max_length=2,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("approved", models.BooleanField(default=False)),
                ("articles", models.ManyToManyField(blank=True, to="words.article")),
                (
                    "language",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="words.language"),
                ),
                ("notes", models.ManyToManyField(blank=True, to="words.note")),
                (
                    "parts_of_speech",
                    models.ManyToManyField(blank=True, to="words.partofspeech", verbose_name="Parts of Speech"),
                ),
            ],
            options={
                "unique_together": {("title", "language")},
            },
        ),
        migrations.CreateModel(
            name="PreviewBundle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("approved", models.BooleanField(default=False)),
                ("preview_words", models.ManyToManyField(blank=True, to="preview.previewword")),
            ],
        ),
    ]
