# Generated by Django 4.2.11 on 2024-03-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preview", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="previewbundle",
            options={"verbose_name": "Bundle"},
        ),
        migrations.AlterModelOptions(
            name="previewword",
            options={"verbose_name": "Word"},
        ),
    ]
