# Generated by Django 4.2.11 on 2024-03-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preview", "0002_alter_previewbundle_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="previewword",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="previewword",
            name="articles",
        ),
        migrations.RemoveField(
            model_name="previewword",
            name="language",
        ),
        migrations.RemoveField(
            model_name="previewword",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="previewword",
            name="parts_of_speech",
        ),
        migrations.DeleteModel(
            name="PreviewBundle",
        ),
        migrations.DeleteModel(
            name="PreviewWord",
        ),
    ]
