# Generated by Django 4.2.11 on 2024-03-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("words", "0001_initial"),
        ("preview", "0003_alter_previewword_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreWord",
            fields=[
                (
                    "word_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="words.word",
                    ),
                ),
            ],
            bases=("words.word",),
        ),
    ]
