# Generated by Django 4.2.11 on 2024-03-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preview", "0005_alter_preword_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="preword",
            options={"verbose_name": "Word"},
        ),
    ]
