# Generated by Django 4.2.11 on 2024-03-27 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0001_initial"),
        ("preview", "0006_alter_preword_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreBundle",
            fields=[
                (
                    "bundle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="words.bundle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bundle",
            },
            bases=("words.bundle",),
        ),
    ]
