# Generated by Django 4.2.11 on 2024-03-28 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0003_rename_name_language_title"),
        ("preview", "0007_prebundle"),
    ]

    operations = [
        migrations.AddField(
            model_name="prebundle",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prebundle",
            name="article",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="words.article"),
        ),
        migrations.AddField(
            model_name="prebundle",
            name="language",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="words.language"),
        ),
        migrations.AddField(
            model_name="prebundle",
            name="part_of_speech",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="words.partofspeech",
                verbose_name="Parts of Speech",
            ),
        ),
    ]
