# Generated by Django 4.2.11 on 2024-03-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preview", "0008_prebundle_approved_prebundle_article_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prebundle",
            name="pre_words",
            field=models.ManyToManyField(blank=True, to="preview.preword"),
        ),
    ]
