# Generated by Django 4.2.11 on 2024-03-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preview", "0009_prebundle_pre_words"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PreBundle",
        ),
    ]
