# Generated by Django 4.2.11 on 2024-03-28 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0003_rename_name_language_title"),
        ("preview", "0010_delete_prebundle"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreBundle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="", null=True)),
                ("approved", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="words.article"),
                ),
                (
                    "language",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="words.language"),
                ),
                (
                    "part_of_speech",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="words.partofspeech",
                        verbose_name="Parts of Speech",
                    ),
                ),
                ("words", models.ManyToManyField(blank=True, to="preview.preword")),
            ],
            options={
                "verbose_name": "Bundle",
            },
        ),
    ]
