# Generated by Django 4.2.11 on 2024-03-28 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0003_rename_name_language_title"),
        ("preview", "0011_prebundle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prebundle",
            name="part_of_speech",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="words.partofspeech",
                verbose_name="Part of Speech",
            ),
        ),
    ]
