# Generated by Django 4.2.11 on 2024-03-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0003_rename_name_language_title"),
        ("preview", "0012_alter_prebundle_part_of_speech"),
    ]

    operations = [
        migrations.AddField(
            model_name="prebundle",
            name="level",
            field=models.CharField(
                choices=[("a1", "A1"), ("a2", "A2"), ("b1", "B1"), ("b2", "B2"), ("c1", "C1"), ("c2", "C2")],
                default="a1",
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="prebundle",
            unique_together={("title", "language")},
        ),
    ]
