# Generated by Django 4.2.11 on 2024-03-28 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preview", "0013_prebundle_level_alter_prebundle_unique_together"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PreBundle",
        ),
    ]
