# Generated by Django 4.2.11 on 2024-03-29 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0003_rename_name_language_title"),
        ("preview", "0015_prebundle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prebundle",
            name="article",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="words.article"
            ),
        ),
    ]
