# Generated by Django 4.2.11 on 2024-03-29 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("words", "0003_rename_name_language_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreWord",
            fields=[
                (
                    "word_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="words.word",
                    ),
                ),
            ],
            options={
                "verbose_name": "Word",
            },
            bases=("words.word",),
        ),
        migrations.CreateModel(
            name="PreBundle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[("a1", "A1"), ("a2", "A2"), ("b1", "B1"), ("b2", "B2"), ("c1", "C1"), ("c2", "C2")],
                        max_length=2,
                    ),
                ),
                ("description", models.TextField(blank=True, default="", null=True)),
                ("in_review", models.BooleanField(default=False, verbose_name="In Review")),
                ("approved", models.BooleanField(default=False)),
                ("merged", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="words.article"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="words.language"),
                ),
                (
                    "part_of_speech",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="words.partofspeech",
                        verbose_name="Part of Speech",
                    ),
                ),
                ("words", models.ManyToManyField(blank=True, to="preview.preword")),
            ],
            options={
                "verbose_name": "Bundle",
                "unique_together": {("title", "language")},
            },
        ),
    ]
