# Generated by Django 4.2.11 on 2024-03-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0003_rename_name_language_title"),
        ("previews", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="prebundle",
            unique_together={("title", "language", "part_of_speech")},
        ),
    ]
