# Generated by Django 4.2.11 on 2024-03-31 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("previews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preword",
            name="parts_of_speech",
        ),
    ]
