# Generated by Django 4.2.11 on 2024-03-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("previews", "0002_alter_prebundle_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prebundle",
            name="words",
            field=models.ManyToManyField(blank=True, to="previews.preword"),
        ),
    ]
