# Generated by Django 4.2.11 on 2024-03-31 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0005_alter_word_part_of_speech"),
        ("previews", "0002_remove_preword_parts_of_speech"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="preword",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="preword",
            name="part_of_speech",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="words.partofspeech",
                verbose_name="Part of Speech",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="preword",
            unique_together={("title", "language", "part_of_speech")},
        ),
    ]
