# Generated by Django 4.2.11 on 2024-03-31 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0006_remove_word_parts_of_speech"),
        ("previews", "0003_alter_preword_unique_together_preword_part_of_speech_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preword",
            name="part_of_speech",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="words.partofspeech",
                verbose_name="Part of Speech",
            ),
        ),
    ]
