# Generated by Django 4.2.11 on 2024-03-31 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("previews", "0004_alter_preword_part_of_speech"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="preword",
            unique_together=set(),
        ),
    ]
