# Generated by Django 4.2.11 on 2024-03-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("previews", "0005_alter_preword_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="preview",
            name="plural",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
